//
// Copyright(C) 1993-1996 Id Software, Inc.
// Copyright(C) 2005-2014 Simon Howard
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// DESCRIPTION: Event handling.
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//

#include <stdlib.h>
#include <stdio.h>
#include "d_event.h"
#include "mem_alloc.h"

#define MAXEVENTS 64

static event_t* g_pEvents;
static int eventHead;
static int eventTail;

// dynamically allocate que, to save more space in DRAM_0 segment
void D_EventsInitQueue()
{
    eventHead = 0;
    eventTail = 0;

    g_pEvents = (event_t*)mem_alloc( sizeof(event_t) * MAXEVENTS );
    if( !g_pEvents ) {
        printf( "Alloc Events queue failed!\n" );
        assert( 0 );
    }
}

//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent(event_t* ev)
{
    g_pEvents[eventHead] = *ev;
    eventHead = (eventHead + 1) % MAXEVENTS;
}

// Read an event from the queue.
event_t* D_PopEvent(void)
{
    event_t *result;

    // No more events waiting.
    if( eventTail == eventHead )
    {
        return NULL;
    }
    
    result = &g_pEvents[eventTail];

    // Advance to the next event in the queue.
    eventTail = (eventTail + 1) % MAXEVENTS;

    return result;
}


